apiVersion: apps/v1
kind: Deployment
metadata:
  name: eaasapi-e-7
spec:
  replicas: 1
  selector:
    matchLabels:
      app: eaasapi-e
  template:
    metadata:
      labels:
        app: eaasapi-e
    spec:
      containers:
      - name: eanginx
        image: localhost:5001/eaasapi-e/eanginx
        ports:
        - name: https
          containerPort: 443
        - name: http
          containerPort: 80
        volumeMounts:
        - mountPath: /var/log/nginx
          name: nginxmount7
        - mountPath: /var/www/html/ACCOUNT
          name: eapersist
        - mountPath: /var/tmp
          name: vartmp

      - name: eaasapi
        image: localhost:5001/eaasapi-e/eaasapi
        volumeMounts:
        - mountPath: /var/log/nginx
          name: nginxmount7
        - mountPath: /var/www/html/ACCOUNT
          name: eapersist
        - mountPath: /var/tmp
          name: vartmp
        - mountPath: /usr/local/bin/
          name: binmount

      volumes:
       - name: eapersist
         hostPath:
           path: /srv/persist/ACCOUNT/www
           type: Directory
       - name: vartmp
         hostPath:
           path: /srv/persist/ACCOUNT/var/tmp
           type: Directory    
       - name: nginxmount7
         hostPath:
           path: /srv/persist/ACCOUNT/log/7
           type: Directory    
       - name: binmount
         hostPath:
           path: /srv/persist/ACCOUNT/bin
           type: Directory    
 
