#!/usr/bin/env bash
mkdir -p /srv/persist/ACCOUNT/cgi/
mkdir -p /srv/persist/ACCOUNT/data/
mkdir -p /srv/persist/ACCOUNT/bin/
mkdir -p /srv/persist/ACCOUNT/www/transfer/
mkdir -p /srv/persist/ACCOUNT/var/tmp/
mkdir -p /srv/persist/ACCOUNT/log/cgi/ 
mkdir -p /srv/persist/ACCOUNT/htdocs/

echo "WARN: opening up /srv/persist/ACCOUNT/www/transfer to 777 permissions for sftp users!"
chmod 777 /srv/persist/ACCOUNT/www/transfer 
echo "WARN: opening up /srv/persist/ACCOUNT/aapche-logs to 777 permissions for webserver system users!"
chmod 777 /srv/persist/ACCOUNT/apache-logs
echo "WARN: opening up /srv/persist/ACCOUNT/htdocs/s to 777 permissions for webserver system users!"
chmod 777 /srv/persist/ACCOUNT/htdocs

chmod +x ACCOUNT-api || echo "WARN: no default backend ACCOUNT-api found found in $(pwd)"
cp ACCOUNT-api /srv/persist/ACCOUNT/bin/ || echo "WARN: the default backend was not copied to /srv/persist/ACCOUNT/bin/"

apt-get install -y apt-transport-https
apt-get install -y aptitude 
aptitude install -y ufw 

ufw allow 30442
ufw allow 30444
ufw allow 30023
ufw enable
ufw reload

echo "Creating a complete backup of deployment files in ~/eaas-deployment-e if that directory isn't this one!"
mkdir ~/eaas-deployment-e/ 2>/dev/null
cp -r ./* ~/eaas-deployment-e/ 2>/dev/null 
echo
echo -e "\e[32mInstall complete!\e[0m"
echo
