#!/usr/bin/env bash

buildlocal () {
  cd $1
  if [ "$1" = eacgi ]; then
    chmod +x secp384r1.cgi
  fi
  docker build -t 127.0.0.1:5000/eaas-api-e/"$1" .
  docker push PRIVATEREPO/eaas-api-e/"$1"
  cd ..
}


mkdir -p /srv/persist/ACCOUNT/cgi/
mkdir -p /srv/persist/ACCOUNT/data/
mkdir -p /srv/persist/ACCOUNT/bin/
mkdir -p /srv/persist/ACCOUNT/www/transfer/
mkdir -p /srv/persist/ACCOUNT/var/tmp/
mkdir -p /srv/persist/ACCOUNT/log/cgi/ 
mkdir -p /srv/persist/ACCOUNT/htdocs/

echo "WARN: opening up /srv/persist/ACCOUNT/www/transfer to 777 permissions for sftp users!"
chmod 777 /srv/persist/ACCOUNT/www/transfer 
echo "WARN: opening up /srv/persist/ACCOUNT/aapche-logs to 777 permissions for webserver system users!"
chmod 777 /srv/persist/ACCOUNT/apache-logs
echo "WARN: opening up /srv/persist/ACCOUNT/htdocs/s to 777 permissions for webserver system users!"
chmod 777 /srv/persist/ACCOUNT/htdocs

chmod +x ACCOUNT-api || echo "WARN: no default backend ACCOUNT-api found found in $(pwd)"
cp ACCOUNT-api /srv/persist/ACCOUNT/bin/ || echo "WARN: the default backend was not copied to /srv/persist/ACCOUNT/bin/"

yum install -y yum-utils
yum-config-manager --add-repo https://download.docker.com/linux/centos/docker-ce.repo
yum install -y docker-ce docker-ce-cli containerd.io firewalld
systemctl start docker
systemctl enable docker

# eaas service ports
firewall-cmd --permanent --add-port=30442/tcp
firewall-cmd --permanent --add-port=30444/tcp
firewall-cmd --permanent --add-port=30023/tcp
# docker ports
firewall-cmd --permanent --add-port=2376/tcp
firewall-cmd --permanent --add-port=2377/tcp
firewall-cmd --permanent --add-port=7946/tcp
firewall-cmd --permanent --add-port=7946/udp
firewall-cmd --permanent --add-port=4789/udp
# web ports
firewall-cmd --permanent --add-port=80/tcp
firewall-cmd --permanent --add-port=8080/tcp
firewall-cmd --permanent --add-port=443/tcp
# admin
firewall-cmd --permanent --add-port=22/tcp

firewall-cmd --reload

echo "Checking for registry."

reglistener=$(docker container ls | awk '{print $2}' | grep registry | wc -l)
if [ $reglistener = 1 ]; then
  echo "local docker registry found..."
else
  echo "No local registry found, starting up local registry."
  docker run -d --restart unless-stopped  -p 127.0.0.1:5000:5000 registry
fi

docker network create --subnet=172.19.0.0/16 dockernetwork || echo "did not create dockernetwork"

buildlocal eaasapi
buildlocal eanginx
buildlocal eaproxy
buildlocal earedis
buildlocal eatransfer
buildlocal eacgi
buildlocal eacgiproxy

echo "Creating a complete backup of deployment files in ~/eaas-deployment-e if that directory isn't this one!"
mkdir ~/eaas-deployment-e/ 2>/dev/null
cp -r ./* ~/eaas-deployment-e/ 2>/dev/null 
echo
echo -e "\e[32mInstall complete!\e[0m"
echo
