#!/usr/bin/env bash

echo "Checking for registry."

reglistener=$(docker container ls | awk '{print $2}' | grep registry:2 | wc -l)
if [ $reglistener = 1 ]; then
  echo "local docker registry found..."
else
  echo "No local registry found, starting up local registry."
  docker run -d --restart unless-stopped -p 5001:5000 registry:2
fi

echo "Building containers..."
cd eanginx
docker build -t eanginx .
cd ../eaasapi
docker build -t eaasapi .
cd ../earedis
docker build -t earedis .
cd ../eacgi
docker build -t eacgi .
cd ../eaproxy
docker build -t eaproxy .
cd ../eacgiproxy
docker build -t eacgiproxy .
cd ../eatransfer
docker build -t eatransfer .
cd ..

docker tag eanginx localhost:5001/eaasapi-e/eanginx
docker push localhost:5001/eaasapi-e/eanginx
docker tag eaasapi localhost:5001/eaasapi-e/eaasapi
docker push localhost:5001/eaasapi-e/eaasapi
docker tag earedis localhost:5001/eaasapi-e/earedis
docker push localhost:5001/eaasapi-e/earedis
docker tag eacgi localhost:5001/eaasapi-e/eacgi
docker push localhost:5001/eaasapi-e/eacgi
docker tag eacgiproxy localhost:5001/eaasapi-e/eacgiproxy
docker push localhost:5001/eaasapi-e/eacgiproxy
docker tag eaproxy localhost:5001/eaasapi-e/eaproxy
docker push localhost:5001/eaasapi-e/eaproxy
docker tag eacgiproxy localhost:5001/eaasapi-e/eacgiproxy
docker push localhost:5001/eaasapi-e/eacgiproxy
docker tag eatransfer localhost:5001/eaasapi-e/eatransfer
docker push localhost:5001/eaasapi-e/eatransfer
