#!/bin/bash
# eaas deployment e shutdown

echo "WARN: This script using regex .\-e.* to match kubernetes delete targets!"

case "$1" in
pod)
for x in $(microk8s.kubectl get all | grep ".\-e.*" | awk '{print $1}' | grep pod); do 
  echo $x
  microk8s.kubectl delete $x
done
;;
service)
for x in $(microk8s.kubectl get all | grep ".\-e.*" | awk '{print $1}' | grep service); do 
  echo $x
  microk8s.kubectl delete $x
done
;;
dep)
for x in $(microk8s.kubectl get all | grep ".\-e.*" | awk '{print $1}' | grep deployments); do 
  echo $x
  microk8s.kubectl delete $x
done
;;
all)
for x in $(microk8s.kubectl get all | grep ".\-e.*" | awk '{print $1}' | grep deployments); do 
  echo $x
  microk8s.kubectl delete $x
done
for x in $(microk8s.kubectl get all | grep ".\-e.*" | awk '{print $1}' | grep service); do 
  echo $x
  microk8s.kubectl delete $x
done
;;
*)
echo "Usage: shutdown-e $option";
echo "Options include: pod dep service all"
exit 1;
esac
