FROM atmoz/sftp:alpine
LABEL maintainer="carefuldata@protonmail.com"
LABEL version="1.0"
LABEL description="Transfer Port SFTP for Eaas API deployment e"

COPY users.conf /etc/sftp/users.conf

EXPOSE 22
